stages:
  - test

.test_template: &test_definition
  stage: test
  # don't start any services (mainly not the default ones)
  services:
  script:
    - dnf -y install $(cat test-deps-fedora.txt)
    - PYTEST_ADDOPTS="-m 'not optional'" tox

test:f24:
  <<: *test_definition
  image: fedora:24

test:latest:
  <<: *test_definition
  image: fedora:latest

test:rawhide:
  <<: *test_definition
  image: fedora:rawhide
