language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
before_install:
  - git submodule update --init --recursive
  - sudo apt-get install liblzma-dev rpm-python
install: 
- pip install -r requirements-devel.txt --use-mirrors
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi

script: python setup.py test -t py.test
