sudo: required
language: python
services: docker
env:
    - DOCKER_IMAGE=fedora:25
    - DOCKER_IMAGE=fedora:latest
    - DOCKER_IMAGE=fedora:rawhide
install: true
before_script:
    - |
        if [ "${TRAVIS_EVENT_TYPE}" = "cron" ]; then
            PYTEST_ADDOPTS="-m 1"
        else
            PYTEST_ADDOPTS="-m 'not optional'"
        fi
script: make PYTEST_ADDOPTS="${PYTEST_ADDOPTS}" test-docker
