language: python
python:
  - "2.7"
  - "3.3"
before_install:
  - git submodule update --init --recursive

install: 
- pip install -r requirements-devel.txt --use-mirrors
- if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install argparse; fi

script: python setup.py test -t py.test
