sudo: required
language: python
services: docker
env:
    - DOCKER_IMAGE=fedora:24
    - DOCKER_IMAGE=fedora:latest
    - DOCKER_IMAGE=fedora:rawhide
install: true
script: make PYTEST_ADDOPTS="$([ "$TRAVIS_EVENT_TYPE" = "cron" ] && echo "-m 1" || echo "-m 'not optional'")" test-docker
